Adding support for reading crt/key from Vault
rnelson0/puppet-certs pull request #35
Opened 2020-09-14 20:51 UTC by ekingme

Adding support for reading crt/key from Vault

2020-09-15 01:28 UTC, rnelson0 commented on spec/defines/vhost_spec.rb
> +    it {
We should test some content as well, I’ll look up the exact matches names tomorrow but something like `.with_content(/TEST/)`, just to make sure we are creating the content as expected.

2020-09-15 01:28 UTC, rnelson0 commented on manifests/vhost.pp
> +  $defaults = { ensure => file, notify => Service[$service] }
I don’t see $defaults in use, we could use that and have the conditionals set the additional content, then have one set of resource declarations outside of it. Do you think that would be understandable, or does the duplication make it easier to read?

2020-09-15 01:28 UTC, rnelson0 commented on Gemfile
> +  gem "rspec-puppet-utils"
This should be added to .sync.yml since this module uses PDK.

2020-09-22 16:10 UTC, codylane requested changes
Hi @ekingme, 

I completed my code review and the changes look good.  The only thing I think we are missing here is since we added the `vault_lookup` function our or `certs::vhost` defined type I feel like we should call out that in order to get `vault_lookup` you need to also download `'jsok/vault', '2.3.0'`.  

So I think it's this syntax, it may not be 100% correct. 

```
  "requirements": [
    {
      "name": "puppet",
      "version_requirement": ">= 4.10.0 < 7.0.0"
    },
    {
      "name": "jsok/vault",
      "version_requirement": "2.3.0"
     }
  ],
```

2020-09-22 17:58 UTC, codylane commented
> Hi @ekingme,
> 
> I completed my code review and the changes look good. The only thing I think we are missing here is since we added the `vault_lookup` function our or `certs::vhost` defined type I feel like we should call out that in order to get `vault_lookup` you need to also download `'jsok/vault', '2.3.0'`.
> 
> So I think it's this syntax, it may not be 100% correct.
> 
> ```
> {
>   "name": "rnelson0-certs",
>   "version": "1.0.1-rc0",
>   "author": "rnelson0",
>   "summary": "SSL Certificate File Management",
>   "license": "Apache-2.0",
>   "source": "https://github.com/rnelson0/puppet-certs",
>   "project_page": "https://github.com/rnelson0/puppet-certs",
>   "issues_url": "https://github.com/rnelson0/puppet-certs/issues",
>   "dependencies": [
>     {
>       "name": "vsok-vault",
>       "version_requirement": ">= 2.0.3 < 3.0.0"
>     }
>   ],
>   "operatingsystem_support": [
>     {
>       "operatingsystem": "RedHat",
>       "operatingsystemrelease": [
>         "6",
>         "7"
>       ]
>     },
>     {
>       "operatingsystem": "CentOS",
>       "operatingsystemrelease": [
>         "6",
>         "7"
>       ]
>     }
>   ],
>   "requirements": [
>     {
>       "name": "puppet",
>       "version_requirement": ">= 4.10.0 < 7.0.0"
>     }
>   ],
>   "pdk-version": "1.18.1",
>   "template-url": "pdk-default#1.18.1",
>   "template-ref": "tags/1.18.1-0-g3d2e75c"
> }
> ```

Also, to be future complaint with PDK I feel as though we should add the `mock_with: ':rspec'` in our ~/.sync.yml.  Here's the full file for reference.

```
---
Gemfile:
  optional:
    ':development':
      - gem: 'github_changelog_generator'
        git: 'https://github.com/skywinder/github-changelog-generator'
        ref: '20ee04ba1234e9e83eb2ffb5056e23d641c7a018'
        condition: "Gem::Version.new(RUBY_VERSION.dup) >= Gem::Version.new('2.2.2')"
Rakefile:
  default_disabled_lint_checks:
    - '140chars'
    - 'arrow_alignment'
spec/spec_helper.rb:
  hiera_config: 'spec/fixtures/hiera.yaml'
  mock_with: ':rspec'
```

2020-09-22 19:55 UTC, rnelson0 commented
I'm going to merge this as is, so we can pull from the branch for testing. Before I release a new forge module, let's get the readme updated (rather than add a hard dependency) and add the mock_with.

2020-09-22 19:55 UTC, merged